services:
  backend:
    container_name: app
    build:
      context: ./app
    working_dir: /app
    # working_dir: /app/app
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    # command: uvicorn server:app --host 0.0.0.0 --port 80 --reload
    command: gunicorn server:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80 --keep-alive 30
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
     - MINIO_ENDPOINT=minio:9000
     - MINIO_ROOT_USER=minio
     - MINIO_ROOT_PASSWORD=minio123
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - minio_data:/data
    ports:
      - "7001:7001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  minio_data:
